---
name: Release
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
      - run: make docs
      - name: Verify no changes after docs build
        run: |
          git diff --exit-code

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: jimeh/release-please-manifest-action@84f33fd2828210488c36f3e0a7e3209252d2ae7d # v3.0.0
        id: release
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - name: MAJOR and MAJOR.MINOR tags
        if: ${{ steps.release.outputs.release_created }}
        uses: jimeh/update-tags-action@e58fa0f2f874a12bf0eb90ef8ab4256808c0f373 # v1.0.1
        with:
          tags: |
            v${{ steps.release.outputs.major }}
            v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
